/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { RunScriptResult, DeployContractExecutionResult } from "@alephium/cli";
import { NetworkId } from "@alephium/web3";
import { TokenFaucet, TokenFaucetInstance } from ".";
import { default as testnetDeployments } from "../.deployments.testnet.json";
import { default as devnetDeployments } from "../.deployments.devnet.json";

export type Deployments = {
  deployerAddress: string;
  contracts: {
    TokenFaucet: DeployContractExecutionResult<TokenFaucetInstance>;
    TokenFaucet_TokenFaucet1?: DeployContractExecutionResult<TokenFaucetInstance>;
    TokenFaucet_TokenFaucet2?: DeployContractExecutionResult<TokenFaucetInstance>;
    TokenFaucet_TokenFaucet3?: DeployContractExecutionResult<TokenFaucetInstance>;
    TokenFaucet_TokenFaucet4?: DeployContractExecutionResult<TokenFaucetInstance>;
  };
};

function toDeployments(json: any): Deployments {
  const contracts = {
    TokenFaucet: {
      ...json.contracts["TokenFaucet"],
      contractInstance: TokenFaucet.at(
        json.contracts["TokenFaucet"].contractInstance.address
      ),
    },
    TokenFaucet_TokenFaucet1:
      json.contracts["TokenFaucet:TokenFaucet1"] === undefined
        ? undefined
        : {
            ...json.contracts["TokenFaucet:TokenFaucet1"],
            contractInstance: TokenFaucet.at(
              json.contracts["TokenFaucet:TokenFaucet1"].contractInstance
                .address
            ),
          },
    TokenFaucet_TokenFaucet2:
      json.contracts["TokenFaucet:TokenFaucet2"] === undefined
        ? undefined
        : {
            ...json.contracts["TokenFaucet:TokenFaucet2"],
            contractInstance: TokenFaucet.at(
              json.contracts["TokenFaucet:TokenFaucet2"].contractInstance
                .address
            ),
          },
    TokenFaucet_TokenFaucet3:
      json.contracts["TokenFaucet:TokenFaucet3"] === undefined
        ? undefined
        : {
            ...json.contracts["TokenFaucet:TokenFaucet3"],
            contractInstance: TokenFaucet.at(
              json.contracts["TokenFaucet:TokenFaucet3"].contractInstance
                .address
            ),
          },
    TokenFaucet_TokenFaucet4:
      json.contracts["TokenFaucet:TokenFaucet4"] === undefined
        ? undefined
        : {
            ...json.contracts["TokenFaucet:TokenFaucet4"],
            contractInstance: TokenFaucet.at(
              json.contracts["TokenFaucet:TokenFaucet4"].contractInstance
                .address
            ),
          },
  };
  return {
    ...json,
    contracts: contracts as Deployments["contracts"],
  };
}

export function loadDeployments(
  networkId: NetworkId,
  deployerAddress?: string
): Deployments {
  const deployments =
    networkId === "testnet"
      ? testnetDeployments
      : networkId === "devnet"
      ? devnetDeployments
      : undefined;
  if (deployments === undefined) {
    throw Error("The contract has not been deployed to the " + networkId);
  }
  const allDeployments: any[] = Array.isArray(deployments)
    ? deployments
    : [deployments];
  if (deployerAddress === undefined) {
    if (allDeployments.length > 1) {
      throw Error(
        "The contract has been deployed multiple times on " +
          networkId +
          ", please specify the deployer address"
      );
    } else {
      return toDeployments(allDeployments[0]);
    }
  }
  const result = allDeployments.find(
    (d) => d.deployerAddress === deployerAddress
  );
  if (result === undefined) {
    throw Error("The contract deployment result does not exist");
  }
  return toDeployments(result);
}
